"""Repository interfaces (Ports).

Services depend on these ``Protocol`` types, never on SQLAlchemy. Two adapters
implement them: an in-memory one (tests + demo) and a SQLAlchemy one
(production). Swapping persistence requires zero service changes — this is the
Dependency Inversion Principle made concrete, and it is why the service tests run
without a database.

Interfaces are split by aggregate (Interface Segregation): a service that only
needs laps doesn't depend on user persistence.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.domain.entities import Assignment, Lap, ReferenceLap, Swim, Swimmer, User, Venue
from app.domain.enums import SwimStatus


@runtime_checkable
class UserRepository(Protocol):
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def list_all(self) -> list[User]: ...


@runtime_checkable
class VenueRepository(Protocol):
    def get(self, venue_id: int) -> Venue | None: ...
    def add(self, venue: Venue) -> Venue: ...
    def list_all(self) -> list[Venue]: ...


@runtime_checkable
class SwimmerRepository(Protocol):
    def get(self, swimmer_id: int) -> Swimmer | None: ...
    def add(self, swimmer: Swimmer) -> Swimmer: ...
    def list_all(self) -> list[Swimmer]: ...


@runtime_checkable
class SwimRepository(Protocol):
    def get(self, swim_id: int) -> Swim | None: ...
    def add(self, swim: Swim) -> Swim: ...
    def update(self, swim: Swim) -> Swim: ...
    def list_all(self) -> list[Swim]: ...
    def list_by_status(self, status: SwimStatus) -> list[Swim]: ...


@runtime_checkable
class AssignmentRepository(Protocol):
    def add(self, assignment: Assignment) -> Assignment: ...
    def delete(self, assignment_id: int) -> None: ...
    def get(self, assignment_id: int) -> Assignment | None: ...
    def get_for_swim(self, swim_id: int) -> Assignment | None: ...
    def list_for_timer(self, timer_id: int) -> list[Assignment]: ...
    def exists(self, swim_id: int, timer_id: int) -> bool: ...


@runtime_checkable
class LapRepository(Protocol):
    def add(self, lap: Lap) -> Lap: ...
    def get_by_timer_swim_seq(self, timer_id: int, swim_id: int, seq: int) -> Lap | None: ...
    def list_for_swim(self, swim_id: int) -> list[Lap]: ...
    def highest_seq_for_swim(self, swim_id: int) -> int | None: ...
    def last_valid_for_swim(self, swim_id: int) -> Lap | None: ...


@runtime_checkable
class ReferenceLapRepository(Protocol):
    def get(self, swim_id: int, lap_no: int) -> ReferenceLap | None: ...
    def upsert(self, ref: ReferenceLap) -> ReferenceLap: ...
    def list_for_swim(self, swim_id: int) -> list[ReferenceLap]: ...
